name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kód letöltése a tárolóból
      uses: actions/checkout@v4

    - name: PHP környezet beállítása
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pdo_sqlite

    - name: .env fájl másolása
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Backend függőségek telepítése
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Node.js beállítása
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Frontend függőségek telepítése és fordítása
      run: |
        npm install
        chmod -R +x node_modules/.bin/
        npm run build

    - name: Laravel App Key generálása
      run: php artisan key:generate

    - name: Teszt adatbázis beállítása
      run: |
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env

    - name: Automatizált tesztek futtatása
      run: php artisan test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Staging környezet Deploy szimulációja
      run: |
        echo "Az alkalmazás tesztelése és buildelése sikeresen befejeződött!"
        echo "Deploy folyamat indítása a Staging szerverre..."
        echo "Kód sikeresen átmásolva a szerverre (Szimulált deploy)."
        echo "A rendszer élesítve van!"